DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS wants CASCADE;

CREATE TABLE countries (
    id serial primary key,
    countryName VARCHAR,
    capital VARCHAR,
    continentName VARCHAR
);

CREATE TABLE trips (
 	id serial primary key,
	city VARCHAR,
	year INTEGER,
	image VARCHAR,
	description VARCHAR,
	country_id integer REFERENCES countries(id)
);

CREATE TABLE wants (
	id serial primary key,
	city VARCHAR,
	country_id integer REFERENCES countries(id)
);

INSERT INTO countries (countryName, capital, continentName) VALUES
('Andorra', 'Andorra la Vella', 'Europe'),
('United Arab Emirates', 'Abu Dhabi', 'Asia'),
('Afghanistan', 'Kabul', 'Asia'),
('Antigua and Barbuda', 'St. Johns', 'North America'),
('Anguilla', 'The Valley', 'North America'),
('Albania', 'Tirana', 'Europe'),
('Armenia', 'Yerevan', 'Asia'),
('Angola', 'Luanda', 'Africa'),
('Antarctica', '', 'Antarctica'),
('Argentina', 'Buenos Aires', 'South America'),
('American Samoa', 'Pago Pago', 'Oceania'),
('Austria', 'Vienna', 'Europe'),
('Australia', 'Canberra', 'Oceania'),
('Aruba', 'Oranjestad', 'North America'),
('Åland', 'Mariehamn', 'Europe'),
('Azerbaijan', 'Baku', 'Asia'),
('Bosnia and Herzegovina', 'Sarajevo', 'Europe'),
('Barbados', 'Bridgetown', 'North America'),
('Bangladesh', 'Dhaka', 'Asia'),
('Belgium', 'Brussels', 'Europe'),
('Burkina Faso', 'Ouagadougou', 'Africa'),
('Bulgaria', 'Sofia', 'Europe'),
('Bahrain', 'Manama', 'Asia'),
('Burundi', 'Bujumbura', 'Africa'),
('Benin', 'Porto-Novo', 'Africa'),
('Saint Barthélemy', 'Gustavia', 'North America'),
('Bermuda', 'Hamilton', 'North America'),
('Brunei', 'Bandar Seri Begawan', 'Asia'),
('Bolivia', 'Sucre', 'South America'),
('Bonaire', 'Kralendijk', 'North America'),
('Brazil', 'Brasília', 'South America'),
('Bahamas', 'Nassau', 'North America'),
('Bhutan', 'Thimphu', 'Asia'),
('Bouvet Island', '', 'Antarctica'),
('Botswana', 'Gaborone', 'Africa'),
('Belarus', 'Minsk', 'Europe'),
('Belize', 'Belmopan', 'North America'),
('Canada', 'Ottawa', 'North America'),
('Cocos [Keeling] Islands', 'West Island', 'Asia'),
('Democratic Republic of the Congo', 'Kinshasa', 'Africa'),
('Central African Republic', 'Bangui', 'Africa'),
('Republic of the Congo', 'Brazzaville', 'Africa'),
('Switzerland', 'Bern', 'Europe'),
('Ivory Coast', 'Yamoussoukro', 'Africa'),
('Cook Islands', 'Avarua', 'Oceania'),
('Chile', 'Santiago', 'South America'),
('Cameroon', 'Yaoundé', 'Africa'),
('China', 'Beijing', 'Asia'),
('Colombia', 'Bogotá', 'South America'),
('Costa Rica', 'San José', 'North America'),
('Cuba', 'Havana', 'North America'),
('Cape Verde', 'Praia', 'Africa'),
('Curacao', 'Willemstad', 'North America'),
('Christmas Island', 'Flying Fish Cove', 'Oceania'),
('Cyprus', 'Nicosia', 'Europe'),
('Czechia', 'Prague', 'Europe'),
('Germany', 'Berlin', 'Europe'),
('Djibouti', 'Djibouti', 'Africa'),
('Denmark', 'Copenhagen', 'Europe'),
('Dominica', 'Roseau', 'North America'),
('Dominican Republic', 'Santo Domingo', 'North America'),
('Algeria', 'Algiers', 'Africa'),
('Ecuador', 'Quito', 'South America'),
('Estonia', 'Tallinn', 'Europe'),
('Egypt', 'Cairo', 'Africa'),
('Western Sahara', 'Laâyoune / El Aaiún', 'Africa'),
('Eritrea', 'Asmara', 'Africa'),
('Spain', 'Madrid', 'Europe'),
('Ethiopia', 'Addis Ababa', 'Africa'),
('Finland', 'Helsinki', 'Europe'),
('Fiji', 'Suva', 'Oceania'),
('Falkland Islands', 'Stanley', 'South America'),
('Micronesia', 'Palikir', 'Oceania'),
('Faroe Islands', 'Tórshavn', 'Europe'),
('France', 'Paris', 'Europe'),
('Gabon', 'Libreville', 'Africa'),
('United Kingdom', 'London', 'Europe'),
('Grenada', 'St. Georges', 'North America'),
('Georgia', 'Tbilisi', 'Asia'),
('French Guiana', 'Cayenne', 'South America'),
('Guernsey', 'St Peter Port', 'Europe'),
('Ghana', 'Accra', 'Africa'),
('Gibraltar', 'Gibraltar', 'Europe'),
('Greenland', 'Nuuk', 'North America'),
('Gambia', 'Bathurst', 'Africa'),
('Guinea', 'Conakry', 'Africa'),
('Guadeloupe', 'Basse-Terre', 'North America'),
('Equatorial Guinea', 'Malabo', 'Africa'),
('Greece', 'Athens', 'Europe'),
('South Georgia and the South Sandwich Islands', 'Grytviken', 'Antarctica'),
('Guatemala', 'Guatemala City', 'North America'),
('Guam', 'Hagåtña', 'Oceania'),
('Guinea-Bissau', 'Bissau', 'Africa'),
('Guyana', 'Georgetown', 'South America'),
('Hong Kong', 'Hong Kong', 'Asia'),
('Heard Island and McDonald Islands', '', 'Antarctica'),
('Honduras', 'Tegucigalpa', 'North America'),
('Croatia', 'Zagreb', 'Europe'),
('Haiti', 'Port-au-Prince', 'North America'),
('Hungary', 'Budapest', 'Europe'),
('Indonesia', 'Jakarta', 'Asia'),
('Ireland', 'Dublin', 'Europe'),
('Israel', '', 'Asia'),
('Isle of Man', 'Douglas', 'Europe'),
('India', 'New Delhi', 'Asia'),
('British Indian Ocean Territory', '', 'Asia'),
('Iraq', 'Baghdad', 'Asia'),
('Iran', 'Tehran', 'Asia'),
('Iceland', 'Reykjavik', 'Europe'),
('Italy', 'Rome', 'Europe'),
('Jersey', 'Saint Helier', 'Europe'),
('Jamaica', 'Kingston', 'North America'),
('Jordan', 'Amman', 'Asia'),
('Japan', 'Tokyo', 'Asia'),
('Kenya', 'Nairobi', 'Africa'),
('Kyrgyzstan', 'Bishkek', 'Asia'),
('Cambodia', 'Phnom Penh', 'Asia'),
('Kiribati', 'Tarawa', 'Oceania'),
('Comoros', 'Moroni', 'Africa'),
('Saint Kitts and Nevis', 'Basseterre', 'North America'),
('North Korea', 'Pyongyang', 'Asia'),
('South Korea', 'Seoul', 'Asia'),
('Kuwait', 'Kuwait City', 'Asia'),
('Cayman Islands', 'George Town', 'North America'),
('Kazakhstan', 'Astana', 'Asia'),
('Laos', 'Vientiane', 'Asia'),
('Lebanon', 'Beirut', 'Asia'),
('Saint Lucia', 'Castries', 'North America'),
('Liechtenstein', 'Vaduz', 'Europe'),
('Sri Lanka', 'Colombo', 'Asia'),
('Liberia', 'Monrovia', 'Africa'),
('Lesotho', 'Maseru', 'Africa'),
('Lithuania', 'Vilnius', 'Europe'),
('Luxembourg', 'Luxembourg', 'Europe'),
('Latvia', 'Riga', 'Europe'),
('Libya', 'Tripoli', 'Africa'),
('Morocco', 'Rabat', 'Africa'),
('Monaco', 'Monaco', 'Europe'),
('Moldova', 'Chişinău', 'Europe'),
('Montenegro', 'Podgorica', 'Europe'),
('Saint Martin', 'Marigot', 'North America'),
('Madagascar', 'Antananarivo', 'Africa'),
('Marshall Islands', 'Majuro', 'Oceania'),
('Macedonia', 'Skopje', 'Europe'),
('Mali', 'Bamako', 'Africa'),
('Myanmar [Burma]', 'Naypyitaw', 'Asia'),
('Mongolia', 'Ulan Bator', 'Asia'),
('Macao', 'Macao', 'Asia'),
('Northern Mariana Islands', 'Saipan', 'Oceania'),
('Martinique', 'Fort-de-France', 'North America'),
('Mauritania', 'Nouakchott', 'Africa'),
('Montserrat', 'Plymouth', 'North America'),
('Malta', 'Valletta', 'Europe'),
('Mauritius', 'Port Louis', 'Africa'),
('Maldives', 'Malé', 'Asia'),
('Malawi', 'Lilongwe', 'Africa'),
('Mexico', 'Mexico City', 'North America'),
('Malaysia', 'Kuala Lumpur', 'Asia'),
('Mozambique', 'Maputo', 'Africa'),
('Namibia', 'Windhoek', 'Africa'),
('New Caledonia', 'Noumea', 'Oceania'),
('Niger', 'Niamey', 'Africa'),
('Norfolk Island', 'Kingston', 'Oceania'),
('Nigeria', 'Abuja', 'Africa'),
('Nicaragua', 'Managua', 'North America'),
('Netherlands', 'Amsterdam', 'Europe'),
('Norway', 'Oslo', 'Europe'),
('Nepal', 'Kathmandu', 'Asia'),
('Nauru', 'Yaren', 'Oceania'),
('Niue', 'Alofi', 'Oceania'),
('New Zealand', 'Wellington', 'Oceania'),
('Oman', 'Muscat', 'Asia'),
('Panama', 'Panama City', 'North America'),
('Peru', 'Lima', 'South America'),
('French Polynesia', 'Papeete', 'Oceania'),
('Papua New Guinea', 'Port Moresby', 'Oceania'),
('Philippines', 'Manila', 'Asia'),
('Pakistan', 'Islamabad', 'Asia'),
('Poland', 'Warsaw', 'Europe'),
('Saint Pierre and Miquelon', 'Saint-Pierre', 'North America'),
('Pitcairn Islands', 'Adamstown', 'Oceania'),
('Puerto Rico', 'San Juan', 'North America'),
('Palestine', '', 'Asia'),
('Portugal', 'Lisbon', 'Europe'),
('Palau', 'Melekeok', 'Oceania'),
('Paraguay', 'Asunción', 'South America'),
('Qatar', 'Doha', 'Asia'),
('Réunion', 'Saint-Denis', 'Africa'),
('Romania', 'Bucharest', 'Europe'),
('Serbia', 'Belgrade', 'Europe'),
('Russia', 'Moscow', 'Europe'),
('Rwanda', 'Kigali', 'Africa'),
('Saudi Arabia', 'Riyadh', 'Asia'),
('Solomon Islands', 'Honiara', 'Oceania'),
('Seychelles', 'Victoria', 'Africa'),
('Sudan', 'Khartoum', 'Africa'),
('Sweden', 'Stockholm', 'Europe'),
('Singapore', 'Singapore', 'Asia'),
('Saint Helena', 'Jamestown', 'Africa'),
('Slovenia', 'Ljubljana', 'Europe'),
('Svalbard and Jan Mayen', 'Longyearbyen', 'Europe'),
('Slovakia', 'Bratislava', 'Europe'),
('Sierra Leone', 'Freetown', 'Africa'),
('San Marino', 'San Marino', 'Europe'),
('Senegal', 'Dakar', 'Africa'),
('Somalia', 'Mogadishu', 'Africa'),
('Suriname', 'Paramaribo', 'South America'),
('South Sudan', 'Juba', 'Africa'),
('São Tomé and Príncipe', 'São Tomé', 'Africa'),
('El Salvador', 'San Salvador', 'North America'),
('Sint Maarten', 'Philipsburg', 'North America'),
('Syria', 'Damascus', 'Asia'),
('Swaziland', 'Mbabane', 'Africa'),
('Turks and Caicos Islands', 'Cockburn Town', 'North America'),
('Chad', 'NDjamena', 'Africa'),
('French Southern Territories', 'Port-aux-Français', 'Antarctica'),
('Togo', 'Lomé', 'Africa'),
('Thailand', 'Bangkok', 'Asia'),
('Tajikistan', 'Dushanbe', 'Asia'),
('Tokelau', '', 'Oceania'),
('East Timor', 'Dili', 'Oceania'),
('Turkmenistan', 'Ashgabat', 'Asia'),
('Tunisia', 'Tunis', 'Africa'),
('Tonga', 'Nukualofa', 'Oceania'),
('Turkey', 'Ankara', 'Asia'),
('Trinidad and Tobago', 'Port of Spain', 'North America'),
('Tuvalu', 'Funafuti', 'Oceania'),
('Taiwan', 'Taipei', 'Asia'),
('Tanzania', 'Dodoma', 'Africa'),
('Ukraine', 'Kiev', 'Europe'),
('Uganda', 'Kampala', 'Africa'),
('U.S. Minor Outlying Islands', '', 'Oceania'),
('United States', 'Washington', 'North America'),
('Uruguay', 'Montevideo', 'South America'),
('Uzbekistan', 'Tashkent', 'Asia'),
('Vatican City', 'Vatican City', 'Europe'),
('Saint Vincent and the Grenadines', 'Kingstown', 'North America'),
('Venezuela', 'Caracas', 'South America'),
('British Virgin Islands', 'Road Town', 'North America'),
('U.S. Virgin Islands', 'Charlotte Amalie', 'North America'),
('Vietnam', 'Hanoi', 'Asia'),
('Vanuatu', 'Port Vila', 'Oceania'),
('Wallis and Futuna', 'Mata-Utu', 'Oceania'),
('Samoa', 'Apia', 'Oceania'),
('Kosovo', 'Pristina', 'Europe'),
('Yemen', 'Sanaa', 'Asia'),
('Mayotte', 'Mamoudzou', 'Africa'),
('South Africa', 'Pretoria', 'Africa'),
('Zambia', 'Lusaka', 'Africa'),
('Zimbabwe', 'Harare', 'Africa');

INSERT INTO trips (city, year, image, description, country_id) VALUES
('Lima', 1994, 'http://luxurylaunches.com/wp-content/uploads/2016/10/lima-peru-1170x677.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry 1500s, when an', 174),
('New York City', 2017, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/9a/e3/1d/freedom-tower.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry' , 233),
('Washington', 2017, 'https://cdn.trolleytours.com/wp-content/uploads/2016/06/washington-dc-capitol-at-night.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry 1500s, when an', 233),
('Madrid', 2017, 'https://www.happycow.net/blog/wp-content/uploads/2015/08/madrid-07.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry 1500s, when an', 68),
('Barcelona', 2011, 'https://www.fattiretours.com/uploads/2208/barcelona%20hero.png', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry 1500s, when an', 68),
('Bogota', 2005,  'https://api.services.trvl.com/backgrounds/images/bogota_1.jpg', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry 1500s, when an', 49);

INSERT INTO wants (city, country_id) VALUES
('Los Angeles', 233),
('Hong Kong', 48),
('Sydney', 56),
('Capetown', 241),
('Lisbon', 178);